1. Split the string

In [ ]:
s= "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string

In [ ]:
planet="Earth"
diameter=12742
star ="The diameter of {p} is {k} Kilometers."
print(star.format(p=planet,k=diameter))


The diameter of Earth is 12742 Kilometers.


3. In this nest dictionary grab the word "hello"


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]


'hello'

4.Numpy

In [ ]:
import numpy as np 


4.1 Create an array of 10 zeros?

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros")
print(array)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 Create an array of 10 fives?


In [ ]:
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5.Create an array of all the even integers from 20 to 35


In [ ]:
a=np.arange(20,35,2)
print(a)

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



7.Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


Pandas

8. Create a dataframe with 3 rows and 2 columns


In [ ]:
import pandas as pd

data=[['vamsi',10],['mahesh',20],['sai',30]]
a=pd.DataFrame(data,columns=['Name','Age',])
print(a)

     Name  Age
0   vamsi   10
1  mahesh   20
2     sai   30


9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import datetime, timedelta

def date_range(start, end):
    delta = end - start  # as timedelta
    days = [start + timedelta(days=i) for i in range(delta.days + 1)]
    return days

start_date = datetime(2023, 1, 1)
end_date = datetime(2023, 2, 10)
print(*date_range(start_date, end_date))


2023-01-01 00:00:00 2023-01-02 00:00:00 2023-01-03 00:00:00 2023-01-04 00:00:00 2023-01-05 00:00:00 2023-01-06 00:00:00 2023-01-07 00:00:00 2023-01-08 00:00:00 2023-01-09 00:00:00 2023-01-10 00:00:00 2023-01-11 00:00:00 2023-01-12 00:00:00 2023-01-13 00:00:00 2023-01-14 00:00:00 2023-01-15 00:00:00 2023-01-16 00:00:00 2023-01-17 00:00:00 2023-01-18 00:00:00 2023-01-19 00:00:00 2023-01-20 00:00:00 2023-01-21 00:00:00 2023-01-22 00:00:00 2023-01-23 00:00:00 2023-01-24 00:00:00 2023-01-25 00:00:00 2023-01-26 00:00:00 2023-01-27 00:00:00 2023-01-28 00:00:00 2023-01-29 00:00:00 2023-01-30 00:00:00 2023-01-31 00:00:00 2023-02-01 00:00:00 2023-02-02 00:00:00 2023-02-03 00:00:00 2023-02-04 00:00:00 2023-02-05 00:00:00 2023-02-06 00:00:00 2023-02-07 00:00:00 2023-02-08 00:00:00 2023-02-09 00:00:00 2023-02-10 00:00:00


10. Create 2D list to DataFrame

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['Number','FName','Age'])
print(df)

   Number FName  Age
0       1   aaa   22
1       2   bbb   25
2       3   ccc   24
